server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.169.1.52:3306/umc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true
    fetchRegistry: true
    service-url:
      defaultZone: http://192.169.1.135:7001/eureka,http://192.168.1.135:7002/eureka
  instance:
    instance-id: payment8002
    ##访问地址可以显示ip地址
    prefer-ip-address: true



mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.chenly.springcloud.entities
