server:
  port: 8084


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.169.1.82:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 192.169.1.82:9000
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
        clientIp: 192.169.1.135


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider